[package]
name = "image_ascii_art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
